In [ ]:
from pyprojroot import here
import polars as p
df = p.read_csv(here('src/data/train.csv'))


df.describe()

shape: (9, 13)
┌────────────┬─────────────┬──────────┬──────────┬───┬───────────┬───────────┬───────┬──────────┐
│ statistic  ┆ PassengerId ┆ Survived ┆ Pclass   ┆ … ┆ Ticket    ┆ Fare      ┆ Cabin ┆ Embarked │
│ ---        ┆ ---         ┆ ---      ┆ ---      ┆   ┆ ---       ┆ ---       ┆ ---   ┆ ---      │
│ str        ┆ f64         ┆ f64      ┆ f64      ┆   ┆ str       ┆ f64       ┆ str   ┆ str      │
╞════════════╪═════════════╪══════════╪══════════╪═══╪═══════════╪═══════════╪═══════╪══════════╡
│ count      ┆ 891.0       ┆ 891.0    ┆ 891.0    ┆ … ┆ 891       ┆ 891.0     ┆ 204   ┆ 889      │
│ null_count ┆ 0.0         ┆ 0.0      ┆ 0.0      ┆ … ┆ 0         ┆ 0.0       ┆ 687   ┆ 2        │
│ mean       ┆ 446.0       ┆ 0.383838 ┆ 2.308642 ┆ … ┆ null      ┆ 32.204208 ┆ null  ┆ null     │
│ std        ┆ 257.353842  ┆ 0.486592 ┆ 0.836071 ┆ … ┆ null      ┆ 49.693429 ┆ null  ┆ null     │
│ min        ┆ 1.0         ┆ 0.0      ┆ 1.0      ┆ … ┆ 110152    ┆ 0.0       ┆ A10   ┆ C        │
│ 25%        ┆ 224.0       ┆ 0.0      ┆ 2.0      ┆ … ┆ null      ┆ 7.925     ┆ null  ┆ null     │
│ 50%        ┆ 446.0       ┆ 0.0      ┆ 3.0      ┆ … ┆ null      ┆ 14.4542   ┆ null  ┆ null     │
│ 75%        ┆ 669.0       ┆ 1.0      ┆ 3.0      ┆ … ┆ null      ┆ 31.0      ┆ null  ┆ null     │
│ max        ┆ 891.0       ┆ 1.0      ┆ 3.0      ┆ … ┆ WE/P 5735 ┆ 512.3292  ┆ T     ┆ S        │
└────────────┴─────────────┴──────────┴──────────┴───┴───────────┴───────────┴───────┴──────────┘

In [ ]:
#количество пассажиров каждого класса
df.group_by("Pclass").len()

shape: (3, 2)
┌────────┬─────┐
│ Pclass ┆ len │
│ ---    ┆ --- │
│ i64    ┆ u32 │
╞════════╪═════╡
│ 1      ┆ 216 │
│ 2      ┆ 184 │
│ 3      ┆ 491 │
└────────┴─────┘

In [ ]:
#количество выживших мужчин и женщин на корабле
df.filter(p.col("Survived") == 1).group_by("Sex").len()

shape: (2, 2)
┌────────┬─────┐
│ Sex    ┆ len │
│ ---    ┆ --- │
│ str    ┆ u32 │
╞════════╪═════╡
│ female ┆ 233 │
│ male   ┆ 109 │
└────────┴─────┘

In [23]:
#часть таблицы с пассажирами, возраст которых больше 44 лет
df.filter(p.col("Age") > 44)

shape: (115, 12)
┌─────────────┬──────────┬────────┬──────────────────┬───┬────────────┬─────────┬───────┬──────────┐
│ PassengerId ┆ Survived ┆ Pclass ┆ Name             ┆ … ┆ Ticket     ┆ Fare    ┆ Cabin ┆ Embarked │
│ ---         ┆ ---      ┆ ---    ┆ ---              ┆   ┆ ---        ┆ ---     ┆ ---   ┆ ---      │
│ i64         ┆ i64      ┆ i64    ┆ str              ┆   ┆ str        ┆ f64     ┆ str   ┆ str      │
╞═════════════╪══════════╪════════╪══════════════════╪═══╪════════════╪═════════╪═══════╪══════════╡
│ 7           ┆ 0        ┆ 1      ┆ McCarthy, Mr.    ┆ … ┆ 17463      ┆ 51.8625 ┆ E46   ┆ S        │
│             ┆          ┆        ┆ Timothy J        ┆   ┆            ┆         ┆       ┆          │
│ 12          ┆ 1        ┆ 1      ┆ Bonnell, Miss.   ┆ … ┆ 113783     ┆ 26.55   ┆ C103  ┆ S        │
│             ┆          ┆        ┆ Elizabeth        ┆   ┆            ┆         ┆       ┆          │
│ 16          ┆ 1        ┆ 2      ┆ Hewlett, Mrs.    ┆ … ┆ 248706     ┆ 16.0    ┆ null  ┆ S        │
│             ┆          ┆        ┆ (Mary D          ┆   ┆            ┆         ┆       ┆          │
│             ┆          ┆        ┆ Kingcome…        ┆   ┆            ┆         ┆       ┆          │
│ 34          ┆ 0        ┆ 2      ┆ Wheadon, Mr.     ┆ … ┆ C.A. 24579 ┆ 10.5    ┆ null  ┆ S        │
│             ┆          ┆        ┆ Edward H         ┆   ┆            ┆         ┆       ┆          │
│ 53          ┆ 1        ┆ 1      ┆ Harper, Mrs.     ┆ … ┆ PC 17572   ┆ 76.7292 ┆ D33   ┆ C        │
│             ┆          ┆        ┆ Henry Sleeper    ┆   ┆            ┆         ┆       ┆          │
│             ┆          ┆        ┆ (My…             ┆   ┆            ┆         ┆       ┆          │
│ …           ┆ …        ┆ …      ┆ …                ┆ … ┆ …          ┆ …       ┆ …     ┆ …        │
│ 858         ┆ 1        ┆ 1      ┆ Daly, Mr. Peter  ┆ … ┆ 113055     ┆ 26.55   ┆ E17   ┆ S        │
│             ┆          ┆        ┆ Denis            ┆   ┆            ┆         ┆       ┆          │
│ 863         ┆ 1        ┆ 1      ┆ Swift, Mrs.      ┆ … ┆ 17466      ┆ 25.9292 ┆ D17   ┆ S        │
│             ┆          ┆        ┆ Frederick Joel   ┆   ┆            ┆         ┆       ┆          │
│             ┆          ┆        ┆ (Ma…             ┆   ┆            ┆         ┆       ┆          │
│ 872         ┆ 1        ┆ 1      ┆ Beckwith, Mrs.   ┆ … ┆ 11751      ┆ 52.5542 ┆ D35   ┆ S        │
│             ┆          ┆        ┆ Richard Leonard… ┆   ┆            ┆         ┆       ┆          │
│ 874         ┆ 0        ┆ 3      ┆ Vander Cruyssen, ┆ … ┆ 345765     ┆ 9.0     ┆ null  ┆ S        │
│             ┆          ┆        ┆ Mr. Victor       ┆   ┆            ┆         ┆       ┆          │
│ 880         ┆ 1        ┆ 1      ┆ Potter, Mrs.     ┆ … ┆ 11767      ┆ 83.1583 ┆ C50   ┆ C        │
│             ┆          ┆        ┆ Thomas Jr (Lily  ┆   ┆            ┆         ┆       ┆          │
│             ┆          ┆        ┆ A…               ┆   ┆            ┆         ┆       ┆          │
└─────────────┴──────────┴────────┴──────────────────┴───┴────────────┴─────────┴───────┴──────────┘

In [ ]:
import pandas as pd
import bottleneck as bn
df = pd.read_csv(here('src/data/train.csv'))

print(f"Средний возраст:{bn.nanmean(df['Age'])}")
print(f"Стандартное отклонение:{bn.nanstd(df['Age'])}")

Средний возраст:29.69911764705882
Стандартное отклонение:14.516321150817317

In [36]:
for row in df.itertuples():
    df['Fare_new'] = df['Fare'] * 1.3

df['Fare_new']

0       9.42500
1      92.66829
2      10.30250
3      69.03000
4      10.46500
         ...
886    16.90000
887    39.00000
888    30.48500
889    39.00000
890    10.07500
Name: Fare_new, Length: 891, dtype: float64

In [ ]:
df = pd.read_csv(here('src/data/Housing.csv'))

df.info()

df['price'] = df['price'].astype('int32')  # Максимум 13 300 000.
df['area'] = df['area'].astype('int16')  # Максимум 16 200 подходит для диапазона int16 (до 32 767).
df['bedrooms'] = df['bedrooms'].astype('int8')  # Максимум 6 помещается в int8 (до 127).
df['bathrooms'] = df['bathrooms'].astype('int8')  # Максимум 4 помещается в int8 (до 127).
df['stories'] = df['stories'].astype('int8')  # Максимум 4 помещается в int8 (до 127).
df['parking'] = df['parking'].astype('int8')  # Максимум 3 помещается в int8 (до 127).
df['mainroad'] = df['mainroad'].map({'yes': 1, 'no': 0}).astype('int8')  # Бинарные значения 'yes'/'no' переводятся в 1/0 и сжимаются в минимальный тип int8 для экономии памяти.
df['guestroom'] = df['guestroom'].map({'yes': 1, 'no': 0}).astype('int8')  # Бинарные значения 'yes'/'no' переводятся в 1/0 и сжимаются в минимальный тип int8 для экономии памяти.
df['basement'] = df['basement'].map({'yes': 1, 'no': 0}).astype('int8')  # Бинарные значения 'yes'/'no' переводятся в 1/0 и сжимаются в минимальный тип int8 для экономии памяти.
df['hotwaterheating'] = df['hotwaterheating'].map({'yes': 1, 'no': 0}).astype('int8')  # Бинарные значения 'yes'/'no' переводятся в 1/0 и сжимаются в минимальный тип int8 для экономии памяти.
df['airconditioning'] = df['airconditioning'].map({'yes': 1, 'no': 0}).astype('int8')  # Бинарные значения 'yes'/'no' переводятся в 1/0 и сжимаются в минимальный тип int8 для экономии памяти.
df['prefarea'] = df['prefarea'].map({'yes': 1, 'no': 0}).astype('int8')  # Бинарные значения 'yes'/'no' переводятся в 1/0 и сжимаются в минимальный тип int8 для экономии памяти.

df.info()
#сжатие больше, чем в 4 раз

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int32
 1   area              545 non-null    int16
 2   bedrooms          545 non-null    int8
 3   bathrooms         545 non-null    int8
 4   stories           545 non-null    int8
 5   mainroad          545 non-null    int8
 6   guestroom         545 non-null    int8
 7   basement          545 non-null    int8
 8   hotwaterheating   545 non-null    int8
 9   airconditioning   545 non-null    int8
 10  parking           545 non-null    int8
 11  prefarea          545 non-null    int8
 12  furnishingstatus  545 non-null    object
dtypes: int16(1), int32(1), int8(10), object(1)
memory usage: 12.9+ KB